### ISSUE TITLE
[Support Request]: 

### ISSUE THREAD

**Issue by dem368** [DCC-EX/EX-Installer#111]
### Version

N/A

### Issue description

When I downloaded Ex-Installer to my Dell laptop Windows 10 computer, I got this file: Unconfirmed 587508.crdownload.  What happened? I tried both the 32 and 64 bit files with the same results.

**Comment by peteGSX** [comment]
This looks like your download has not completed successfully. Has your antivirus blocked the download by any chance?

**Comment by dem368** [comment]
Found that Microsoft Edge would not download the file while Google Chrome would.  I now have both the 64 and 32 bit versions.
________________________________

**Comment by peteGSX** [comment]
Excellent, glad to hear you got it sorted!
