### ISSUE TITLE
Bug Report: Clone/unknown devices don't display COM port

### ISSUE THREAD

**Issue by peteGSX** [DCC-EX/EX-Installer#12]
### Version

The only one

### Bug description

When detecting attached devices, clones/unknown devices don't display the COM port they're attached to.

### Steps to reproduce the bug

Connect a clone device, progress to detect devices, and clone/unknown will be displayed without COM port.

### Expected behaviour

COM port should be displayed.

**Comment by pmantoine** [comment]
![Screenshot 2023-06-13 115452](https://github.com/DCC-EX/EX-Installer/assets/85058380/4ad7b5c1-bee0-4bb4-90f7-4b23ecf19f79)

Screenshot of two serial devices found, one of which (the bottom one) was a Mega+WiFI

**Comment by pmantoine** [comment]
![image](https://github.com/DCC-EX/EX-Installer/assets/85058380/89020dec-e14b-4be1-aee5-5f3dec74bbbd)
The devices in Device Manager

**Comment by peteGSX** [comment]
Missed adding the COM port to the text variable for both unknown devices and devices that have multiple possible matches. Fixed, and will reflect in the next .exe build.
