### ISSUE TITLE
[Feature Request]: Add automatic device detection

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/EX-Installer#32]
### Problem/idea statement

Currently, any device that was plugged in previously is shown as a potential target. It would be nice if it worked like the Arduino IDE and Steve Todds image where it tests the com port and gets an ID back.

### Alternatives or workarounds

no issues

**Comment by peteGSX** [comment]
This is already in place. Any device the Arduino CLI recognises shows up, and any devices it doesn't recognise has the information available by the serial port made available.
