### ISSUE TITLE
[Feature Request]: Add verbose option for compiling and uploading

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/EX-Installer#33]
### Problem/idea statement

Unless I missed it, it would be nice to check a box for detailed compile and upload messages

### Alternatives or workarounds

none

**Comment by peteGSX** [comment]
There is no option available to display ongoing progress during the compile or upload phases.

The only increased output would be to separate out the compile, attach, and then uploaded phases to at least show the output of each process.
